path: /Users/pyretttt/dev/XCDoTo/.XCDoTo.yaml
title: Tinkoff
isDisclosed: true
tasks:
- id: C4FFA658-6077-4C01-B868-6723A326FC07
  title: ''
  release: ''
  author: ''
  priority: normal
  taskDescription: ''
- id: CB50298A-32D3-431E-ADCB-A867B10C0784
  title: ''
  release: ''
  author: ''
  priority: normal
  taskDescription: ''
- id: E0731E26-405D-4DE9-9D9E-F88AD38309FE
  title: ''
  release: ''
  author: ''
  priority: normal
  taskDescription: ''
- id: B5FA0CEA-5662-4134-94BD-109707DDADE5
  title: ''
  release: ''
  author: ''
  priority: normal
  taskDescription: ''
